### ISSUE TITLE
Sometimes plots with no pens don't show the plot pen list

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1587]
To reproduce:

1. Create a model with a plot
2. Delete the plots plot pen
3. Close and reopen the plot editor

It will sometimes look like this:

<img width="668" alt="screen shot 2018-03-06 at 10 04 41 am" src="https://user-images.githubusercontent.com/28215/37043464-4bc64644-2126-11e8-8c31-894a71bca959.png">

Switching windows may be required in there somewhere.

In reality, the window is actually just sized too long. Expanding it will reveal the pen list.

**Comment by mrerrormessage** [comment]
It is unclear whether this is a NetLogo bug or not. For users who see it, it happens sporadically but not reproducibly. It seems very possible it's connected to [this Java bug](https://bugs.openjdk.java.net/browse/JDK-8189346?jql=text%20~%20%22swing%20dialog%20size%22%20ORDER%20BY%20created%20DESC) and possibly in some strange way to Mac OS. If there's ever an easily-reproducible case this should be fixed.

**Comment by ERSUCC** [comment]
The layout manager for this dialog has changed since this bug report, and this issue has not been reported since then. I highly doubt that this is still reproducible at this point.
