### ISSUE TITLE
Publish NetLogo on Flathub

### ISSUE THREAD

**Issue by danielvartan** [NetLogo/NetLogo#2547]
Hi there,

I’d like to suggest packaging and maintaining NetLogo as a [Flatpak](https://flatpak.org/) for Linux users.

Right now, downloading and installing NetLogo on Linux isn’t as straightforward as it could be. [Flatpaks](https://flatpak.org/) are one of the most widely used and secure ways to distribute applications on Linux, and publishing NetLogo on [Flathub](https://flathub.org/) would make installation much simpler.

This wouldn’t just benefit Linux users—it would also align with NetLogo’s commitment to open-source software.

Thanks for considering it!

**Comment by SethTisue** [comment]
I'd suggest consolidating this under https://github.com/NetLogo/NetLogo/issues/863

**Comment by ERSUCC** [comment]
I'm not sure that this is a good idea, because our current model requires us to ship all four bundled apps (NetLogo, NetLogo 3D, HubNet Client, and BehaviorSearch) at the same time. We don't want people to have mismatched versions, for example NetLogo 6.4.0 and NetLogo 3D 7.0.0, because it can cause compatibility issues. Also, bundled resources for each version need to be in specific locations relative to the applications, they aren't bundled with the applications themselves. But if Flatpak provides a mechanism for shipping bundles of multiple applications at the same time, we can look into it.

**Comment by danielvartan** [comment]
Good points, @ERSUCC.

I’m not entirely sure, but it looks like Flatpak does provide a mechanism for shipping bundles. For example, see the [LibreOffice Flatpak bundle](https://flathub.org/en/apps/org.libreoffice.LibreOffice).

**Comment by danielvartan** [comment]
Hi @SethTisue,  @ERSUCC , and @TheBizzle ,

I've created a [Flatpak](https://flatpak.org/) for NetLogo! It took some time, but the process was relatively straightforward since NetLogo bundles most of its dependencies.

I've named it [`LogoPak`](https://github.com/danielvartan/logopak). The package includes all four NetLogo applications (NetLogo, NetLogo 3D, HubNet Client, and BehaviorSearch, the whole package) running version 7.0.3. It also registers desktop files, file icons, and MIME types for NetLogo model files, allowing users to interact with NetLogo just like any other native application on their system.

https://github.com/danielvartan/logopak

Please give it a try and let me know how it works for you. I believe this could be an excellent distribution method for NetLogo on Linux, alongside the existing deb packages.

I'm planning to publish this on [Flathub](https://flathub.org), but I'd be happy to transfer the repository to you if you think this is the right direction for the project.

<img width="217" height="250" alt="Image" src="https://github.com/user-attachments/assets/070d49c1-7821-472f-8375-9db7b13949c0" />

<img width="1172" height="592" alt="Image" src="https://github.com/user-attachments/assets/5d5229dc-c093-46bd-ab2f-0813b17448a4" />

**Comment by ERSUCC** [comment]
@danielvartan This is awesome, it's great to have a better way to distribute NetLogo on Linux! The only thing that is unclear to me is how this distribution would deal with the supporting files we currently include in the release, such as the `runtime`, `extensions`, and `models` directories. Currently, many features of NetLogo rely on the specific directory structure of the release, so the app would not be functional if those were not preserved when installing the package. Let me know if I'm misunderstanding and this is not an issue!

**Comment by danielvartan** [comment]
@ERSUCC, all NetLogo files are included (models, extensions, runtime, etc). Is the same tarball bundle, but installed in a sandboxed environment.

**Comment by ERSUCC** [comment]
Ok, great! I didn't see any of those files in the repo you linked, so I wasn't sure. If it's the same tar archive as the one we already distribute, though, then what is the benefit of hosting it on Flatpak? If I were a Linux user, I would prefer to just download the tar and run the installation script, but maybe I'm missing something.

**Comment by danielvartan** [comment]
The advantages are numerous. Here are some key benefits:

- **Flathub integration**: NetLogo will be available on [Flathub](https://flathub.org), one of the most widely used app stores for Linux (probably the future for any application in the OS), with distribution-independent compatibility.
- **One-click installation**: Users can install NetLogo with a single click, complete with documentation and reviews, just like any other app store.
- **Complete system integration**: The installation includes desktop file registration, file icons, and MIME type associations (file associations), allowing users to work with NetLogo as a native application, similar to the experience on Windows and macOS. This level of integration is not currently available for Linux.
- **Enhanced security**: NetLogo runs in a sandboxed environment, providing improved security for users.

Here is how NetLogo would appear in the Flathub store:

<img width="1250" height="885" alt="Image" src="https://github.com/user-attachments/assets/17f4bc6b-e872-4477-b964-665544cb26c8" />

**Comment by danielvartan** [comment]
Currently, NetLogo installation on Linux is not user-friendly and lacks complete system integration. While advanced users can work around this, most Linux users today expect a seamless experience. This Flatpak will provide the same smooth installation process available on Windows and macOS.

@TheBizzle's comment express these current limitations: https://github.com/NetLogo/NetLogo/issues/863#issuecomment-3281950114

**Comment by ERSUCC** [comment]
The integration you mentioned is actually already available through the installation script that we ship with the Linux release, however file icons don't display properly when you run the app, due to annoying Java restrictions. If using Flatpak solves this problem, that would be fantastic! The other advantages you mentioned sound good to me as well, nothing to say there.

It would be great to test this out for our upcoming release of NetLogo 7.0.4. If it seems like people prefer it, then we can work on getting your work integrated with the normal release process!

**Comment by danielvartan** [comment]
Good idea! This could be included in the announcement for the next release.

I don't know if NetLogo collects download statistics, but it would be valuable to compare downloads between the traditional installation method and Flatpak.

**Comment by ERSUCC** [comment]
Yes, we collect download statistics from [netlogo.org](https://netlogo.org/download), so it would be easy to compare. I suspect it will take more than one release of users being aware of alternative download methods before we can have truly meaningful data, though.

**Comment by emstruong** [comment]
Just commenting to show my support for having NetLogo on Flathub -- it'd make it a lot more appealing for Linux users to try it  out quickly...

**Comment by TheBizzle** [comment]
On Ubuntu, I don't get proper icons for `.nlogox` files in Nautilus:

<img width="189" height="249" alt="Image" src="https://github.com/user-attachments/assets/9aa62f3c-340d-4cff-b819-b4a341f7f1aa" />

If that's expected, so it goes; it's clearly not any worse than the previous situation.

One issue that I found is that, when we try to open the web browser for viewing "Quick Help" documentation (hotkey: F1, while the cursor is on some NetLogo code), NetLogo gives an error and fails to open the browser.

Also, LogoPak still seems to install only NetLogo 7.0.3, and not 7.0.4.

But everything else works great! 😎 👍   Is there a reason you haven't uploaded it to FlatHub, @danielvartan?

**Comment by danielvartan** [comment]
> LogoPak still seems to install only NetLogo 7.0.3, and not 7.0.4.

I just updated `LogoPak` to NetLogo 7.0.4. :)

> Is there a reason you haven't uploaded it to FlatHub?

I was waiting for you guys to test it and to see whether it could be distributed as an official format. As I mentioned before, I would happily transfer the `LogoPak` code and repository to NetLogo if that were the case.

I plan to publish it on Flathub at some point.

> On Ubuntu, I don't get proper icons for .nlogox files in Nautilus.

That's odd, since Flatpak is designed to be consistent across Linux installations. This might be a cache issue. Try logging out and back in to see if it persists.

> One issue that I found is that, when we try to open the web browser for viewing "Quick Help" documentation (hotkey: F1, while the cursor is on some NetLogo code), NetLogo gives an error and fails to open the browser.

I was able to reproduce this error on Arch. Thank you for reporting it! It is now fixed.

**Comment by TheBizzle** [comment]
> This might be a cache issue. Try logging out and back in to see if it persists.

I restarted, but still see no icons.  But I'm fine with that.

> I was waiting for you guys to test it and to see whether it could be distributed as an official format. As I mentioned before, I would happily transfer the LogoPak code and repository to NetLogo if that were the case.

Our group already has an enormous amount of stuff that we maintain, relative to the size of our team.  So my first preference is for us to not to take on more.

I like LogoPak, it works, and it's useful to the community.  I encourage you to own and distribute it.
